apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "quarkus-app"
  annotations:
    argocd/app-name: quarkus-app-dev
    backstage.io/kubernetes-id: quarkus-app
    backstage.io/kubernetes-namespace: quarkus-app-dev
    janus-idp.io/tekton-enabled : 'true'
    github.com/project-slug: janus-demo/quarkus-app
    quay.io/repository-slug: "janus-demo/quarkus-app"
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-x7g75.x7g75.sandbox243.opentlc.com/#https://github.com/janus-demo/quarkus-app?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-x7g75.x7g75.sandbox243.opentlc.com/#https://github.com/janus-demo/quarkus-app?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "group:default/rd"
  providesApis:
    - "quarkus-app"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "quarkus-app"
spec:
  type: openapi
  lifecycle: production
  owner: "group:default/rd"
  definition:
    $text: ./openapi.yaml
